name: flutter_bloc_testing
description: Practicing Flutter BLoC

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  bloc_test: 
  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.0
  test: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
